<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0;net10.0</TargetFrameworks>
    <AssemblyName>QS3D.Core</AssemblyName>
    <RootNamespace>QS3D.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
